name: CD-Run Workflow
on:
  workflow_run:
    workflows: ['CD Workflow']
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Connecting to AliCloud and run latest image.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_PRIVATE_KEY }}
          script: |
            HOST_LOG_PATH=/var/local/log/${{ github.repository }}
            IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/taccisum-online
            CONTAINER_NAME=taccisum-online
            PORT=8080
            mkdir -p $HOST_LOG_PATH
            docker pull $IMAGE_TAG
            docker rm -f $CONTAINER_NAME
            docker run \
            -p $PORT:8080 \
            -v $HOST_LOG_PATH:/var/local/log \
            -v /root/script:/usr/local/my_script \
            -d \
            --name $CONTAINER_NAME \
            $IMAGE_TAG \
              --spring.profiles.active=prod \
              --spring.datasource.password=${{ secrets.MYSQL_PASSWORD }}
      - name: send email via pigeon
        run: curl -X POST "http://120.25.107.93:8082/messages?sender=robot_01%40smtp.66cn.top&target=514162920%40qq.com&templateId=7"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Do nothing beacuse of "CD Workflow" is failure.'
